### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jmacaya-ntd** [evanlucas/reset-date-cache#5]
Hello!

I'm having trouble to install this module under Node 14. The error I see seems related to changes v8 headers, but I'm not sure of how to proceed to fix it:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.10.1 | darwin | x64
gyp info find Python using Python version 2.7.17 found at "/usr/local/opt/python@2/bin/python2.7"
gyp http GET https://nodejs.org/download/release/v14.10.1/node-v14.10.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v14.10.1/node-v14.10.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v14.10.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v14.10.1/SHASUMS256.txt
gyp info spawn /usr/local/opt/python@2/bin/python2.7
gyp info spawn args [
gyp info spawn args   '/Users/jmacaya/.nvm/versions/node/v14.10.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jmacaya/package/node_modules/reset-date-cache/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jmacaya/.nvm/versions/node/v14.10.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jmacaya/Library/Caches/node-gyp/14.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jmacaya/.nvm/versions/node/v14.10.1/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jmacaya/Library/Caches/node-gyp/14.10.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jmacaya/package/node_modules/reset-date-cache',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/resetdatecache/src/binding.o
In file included from ../src/binding.cc:1:
In file included from ../../nan/nan.h:190:
../../nan/nan_maybe_43_inl.h:88:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../src/binding.cc:1:
In file included from ../../nan/nan.h:195:
In file included from ../../nan/nan_converters.h:59:
../../nan/nan_converters_43_inl.h:18:1: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
X(Boolean)
^~~~~~~~~~
../../nan/nan_converters_43_inl.h:15:26: note: expanded from macro 'X'
  return val->To ## TYPE(GetCurrentContext());                                 \
                         ^~~~~~~~~~~~~~~~~~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:2848:37: note: passing argument to parameter 'isolate' here
  Local<Boolean> ToBoolean(Isolate* isolate) const;
                                    ^
In file included from ../src/binding.cc:1:
In file included from ../../nan/nan.h:195:
In file included from ../../nan/nan_converters.h:59:
../../nan/nan_converters_43_inl.h:34:1: error: no viable conversion from 'v8::Local<v8::Context>' to 'v8::Isolate *'
X(bool, Boolean)
^~~~~~~~~~~~~~~~
../../nan/nan_converters_43_inl.h:31:29: note: expanded from macro 'X'
  return val->NAME ## Value(GetCurrentContext());                              \
                            ^~~~~~~~~~~~~~~~~~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:2858:30: note: passing argument to parameter 'isolate' here
  bool BooleanValue(Isolate* isolate) const;
                             ^
In file included from ../src/binding.cc:1:
In file included from ../../nan/nan.h:196:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:107:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:190:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:190:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:194:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:4446:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/binding.cc:1:
In file included from ../../nan/nan.h:196:
In file included from ../../nan/nan_new.h:189:
../../nan/nan_implementation_12_inl.h:345:37: error: too few arguments to function call, expected 2, have 1
  return v8::StringObject::New(value).As<v8::StringObject>();
         ~~~~~~~~~~~~~~~~~~~~~      ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:5847:3: note: 'New' declared here
  static Local<Value> New(Isolate* isolate, Local<String> value);
  ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:816:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:188:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:108:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:830:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:181:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:108:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:844:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:174:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:108:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:890:53: error: too few arguments to function call, single argument 'context' was not specified
      v8::Local<v8::String> string = from->ToString();
                                     ~~~~~~~~~~~~~~ ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:2810:3: note: 'ToString' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
  ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8config.h:431:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:900:37: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'char *'
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                    ^~~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3037:26: note: passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1371:43: error: no matching member function for call to 'Get'
    v8::Local<v8::Value> a = New(handle)->Get(kCallbackIndex);
                             ~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1372:49: error: no matching member function for call to 'Get'
    v8::Local<v8::Value> b = New(other.handle)->Get(kCallbackIndex);
                             ~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1403:38: error: no matching member function for call to 'Get'
    return scope.Escape(New(handle)->Get(kCallbackIndex)
                        ~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1409:25: error: no matching member function for call to 'Get'
    return New(handle)->Get(kCallbackIndex)->IsUndefined();
           ~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1447:9: error: no matching member function for call to 'Get'
        Get(kCallbackIndex).As<v8::Function>();
        ^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1457:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:188:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/node.h:108:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1518:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1524:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(key, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1530:28: error: no matching member function for call to 'Set'
    New(persistentHandle)->Set(index, value);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3670:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3673:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1536:32: error: no matching member function for call to 'Get'
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1542:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(key));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
../../nan/nan.h:1547:48: error: no matching member function for call to 'Get'
    return scope.Escape(New(persistentHandle)->Get(index));
                        ~~~~~~~~~~~~~~~~~~~~~~~^~~
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3717:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
/Users/jmacaya/Library/Caches/node-gyp/14.10.1/include/node/v8.h:3720:43: note: candidate function not viable: requires 2 arguments, but 1 was provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
                                          ^
In file included from ../src/binding.cc:1:
In file included from ../../nan/nan.h:2192:
../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make: *** [Release/obj.target/resetdatecache/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jmacaya/.nvm/versions/node/v14.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/jmacaya/.nvm/versions/node/v14.10.1/bin/node" "/Users/jmacaya/.nvm/versions/node/v14.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jmacaya/package/node_modules/reset-date-cache
gyp ERR! node -v v14.10.1
gyp ERR! node-gyp -v v5.1.0
```

**Comment by prabhakar-patil** [comment]
I am facing same issue with reset-date-cache@1.0.4 on following versions
1.  nodejs - v10.16.3 and npm - 6.9.0
2.  nodejs - v12.19.0 and npm - 6.14.8

Tried to install reset-date-cache@1.0.2, got successfully installed but did not get expected result after calling reset() method. Timezone changes did not reset v8's date cache.
